name: Feature request
description: Suggest a new feature or idea for the DevWinUI
title: "[Feature]: "
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: feature proposal
      description: Suggest a new feature or idea
      placeholder: |
        A clear and concise description of what you want to happen
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
      placeholder: |
        Add any other context or screenshots about the feature request here.